ФП-11 "add-database"
lap-lik/java-filmorate pull request #7
Opened 2024-01-31 00:37 UTC by lap-lik

2024-02-12 19:17 UTC, Fleaman777 requested changes

2024-02-12 19:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoDBImpl.java
> +        String str = resultSet.getString("friends_ids");
str - слишком общее название

2024-02-12 19:17 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/AbstractDaoTest.java
> +}
выделение общих вещей во что-то абстрактное конечно хорошо, но не всегда все можно переместить. 

например в этом классе есть вещи, которые не должны пересекаться, и их наличие в другом классе будет лишнем, а значит не совсем верным 

например в классе GenreDaoDBImplTest не используются юзера, но по факту они есть, что не очень хорошо

2024-02-12 19:17 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoDBImplTest.java
> +    void save_Invalid_ReleaseDate() {
в названии можно еще указывать, какой ожидается результат

2024-02-12 19:17 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoDBImplTest.java
> +    void update() {
название тест метода лучше делать отличным от названия основного метода, что бы, например, такой метод было проще искать по всему коду, не отвлекаясь на тестовые

хорошо в названии указать условие при котором выполняется тест и ожидаемый результат,
аналогично в других местах

2024-02-12 19:17 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoDBImplTest.java
> +        setUpUsers();
почему бы не вынести этот вызов в setUp метод, все равно он вызывается во всем тестовых методах 

аналагично можно сделать с другими вещами

2024-02-12 19:37 UTC, lap-lik commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +                        .collect(Collectors.joining("\n")));
Вынес с отдельный метод.

2024-02-12 19:52 UTC, lap-lik commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoDBImpl.java
> +            int isFilmDelete = jdbcTemplate.update(DELETE_FILM_BY_ID, filmId);
Скорректировал во всех классах

2024-02-12 19:53 UTC, lap-lik commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoDBImpl.java
> +        String str = resultSet.getString("friends_ids");
Изменил на "arrayIds"

2024-02-12 20:21 UTC, lap-lik commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("END endpoint `method:POST /users` (create user), response: {}.", response);
Исправил

2024-02-12 20:22 UTC, lap-lik commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("END endpoint `method:GET /films` (get all films), response-size: {}.", response.size());
Исправил, оставил только логи старта

2024-02-13 13:49 UTC, lap-lik commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoDBImplTest.java
> +    void save_Invalid_ReleaseDate() {
Исправлены названия, с учетом в названии указаны условие при котором выполняется тест и ожидаемый результат

2024-02-13 13:50 UTC, lap-lik commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoDBImplTest.java
> +    void update() {
Исправлены названия, с учетом в названии указаны условие при котором выполняется тест и ожидаемый результат

2024-02-13 14:13 UTC, lap-lik commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoDBImplTest.java
> +        setUpUsers();
Распределил создание экземпляров объектов по классам и убрал дублирование кода вызова методов setUp()

2024-02-13 14:13 UTC, lap-lik commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/AbstractDaoTest.java
> +}
Распределил создание экземпляров объектов по классам и убрал дублирование кода вызова методов setUp()

2024-02-14 09:19 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoDBImplTest.java
> +    void testDeleteByUserIdResultUserDeleted() {
отличные названия

2024-02-14 09:24 UTC, merged